<!DOCTYPE html>
<html>
<head>
    <title>Laporan Bulanan - {{ $bulanTahun }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; margin:0; padding:0; }
        .header { display:flex; align-items:center; margin-bottom:10px; border-bottom:2px solid #4CAF50; padding-bottom:10px; }
        .header img { width:80px; margin-right:15px; }
        .company-info { flex:1; text-align:center; font-size:14px; line-height:1.3; }
        .company-info strong { font-size:16px; }
        .report-title { text-align:center; font-size:20px; font-weight:bold; margin:15px 0 25px 0; color:#4CAF50; }
        table { border-collapse: collapse; width:100%; font-size:12px; }
        th, td { border:1px solid #ccc; padding:8px 10px; text-align:center; }
        th { background-color:#4CAF50; color:#fff; }
        tbody tr:nth-child(odd) { background-color:#f9f9f9; }
        .right { text-align:right; }
        .bold { font-weight:bold; }
        .subtotal td { background-color:#e0f7fa; font-weight:bold; }
        .grandtotal td { background-color:#b2ebf2; font-weight:bold; border-top:2px solid #4CAF50; }
        .footer { margin-top:30px; text-align:center; font-size:10px; color:#777; }
    </style>
</head>
<body>
    <div class="header">
        <img src="{{ public_path('img/logo2.jpg') }}" alt="Logo">
        <div class="company-info">
            {{-- <strong>{{ array_key_first($outletsData) }}</strong><br> --}}
            <span>Laporan Bulanan</span>
        </div>
    </div>

    <div class="report-title">
        {{ $bulanTahun }}
    </div>

    @foreach($outletsData as $outletName => $rows)
        @if($outletName !== 'GRAND TOTAL')
            <h4>{{ $outletName }}</h4>
            <table>
                <thead>
                    <tr>
                        <th>Tanggal</th>
                        <th>Sales</th>
                        <th>CU</th>
                        <th>AC</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($rows as $row)
                        @php
                            $isSubtotal = $row['tanggal'] === 'SUBTOTAL';
                        @endphp
                        <tr class="{{ $isSubtotal ? 'subtotal' : '' }}">
                            <td class="{{ $isSubtotal ? 'bold' : '' }}">{{ $row['tanggal'] }}</td>
                            <td class="right">{{ number_format($row['Price']) }}</td>
                            <td class="right">{{ $row['Quantity'] }}</td>
                            <td class="right">{{ $row['Totals'] }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <br>
        @endif
    @endforeach

    @if(isset($outletsData['GRAND TOTAL']))
        <table>
            <thead>
                <tr>
                    <th colspan="1">GRAND TOTAL</th>
                    <th>Sales</th>
                    <th>CU</th>
                    <th>AC</th>
                </tr>
            </thead>
            <tbody>
                @foreach($outletsData['GRAND TOTAL'] as $row)
                    <tr class="grandtotal">
                        <td class="bold">{{ $row['tanggal'] }}</td>
                        <td class="right">{{ number_format($row['Price']) }}</td>
                        <td class="right">{{ $row['Quantity'] }}</td>
                        <td class="right">{{ $row['Totals'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        Generated by Geprekin System
    </div>
</body>
</html>
